// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenGeoPoint sovren geo point
//
// swagger:model Sovren.GeoPoint
type SovrenGeoPoint struct {

	// latitude
	Latitude float32 `json:"Latitude,omitempty"`

	// longitude
	Longitude float32 `json:"Longitude,omitempty"`

	// raw geo code response
	RawGeoCodeResponse string `json:"RawGeoCodeResponse,omitempty"`

	// source
	Source string `json:"Source,omitempty"`
}

// Validate validates this sovren geo point
func (m *SovrenGeoPoint) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren geo point based on context it is used
func (m *SovrenGeoPoint) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenGeoPoint) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenGeoPoint) UnmarshalBinary(b []byte) error {
	var res SovrenGeoPoint
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
