// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenMatchSettings sovren match settings
//
// swagger:model Sovren.MatchSettings
type SovrenMatchSettings struct {

	// position titles ignore single word variations
	PositionTitlesIgnoreSingleWordVariations bool `json:"PositionTitlesIgnoreSingleWordVariations,omitempty"`

	// position titles must have an exact match
	PositionTitlesMustHaveAnExactMatch bool `json:"PositionTitlesMustHaveAnExactMatch,omitempty"`
}

// Validate validates this sovren match settings
func (m *SovrenMatchSettings) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren match settings based on context it is used
func (m *SovrenMatchSettings) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenMatchSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenMatchSettings) UnmarshalBinary(b []byte) error {
	var res SovrenMatchSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
