// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenParserModelResumeSalary sovren parser model resume salary
//
// swagger:model Sovren.Parser.Model.Resume.Salary
type SovrenParserModelResumeSalary struct {

	// amount
	Amount float64 `json:"Amount,omitempty"`

	// currency
	Currency string `json:"Currency,omitempty"`
}

// Validate validates this sovren parser model resume salary
func (m *SovrenParserModelResumeSalary) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren parser model resume salary based on context it is used
func (m *SovrenParserModelResumeSalary) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenParserModelResumeSalary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenParserModelResumeSalary) UnmarshalBinary(b []byte) error {
	var res SovrenParserModelResumeSalary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
