// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenParserModelNameValue sovren parser model name value
//
// swagger:model Sovren.Parser.Model.NameValue
type SovrenParserModelNameValue struct {

	// normalized
	Normalized string `json:"Normalized,omitempty"`

	// raw
	Raw string `json:"Raw,omitempty"`
}

// Validate validates this sovren parser model name value
func (m *SovrenParserModelNameValue) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren parser model name value based on context it is used
func (m *SovrenParserModelNameValue) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenParserModelNameValue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenParserModelNameValue) UnmarshalBinary(b []byte) error {
	var res SovrenParserModelNameValue
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
