// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenParserModelResumeResumeTaxonomy sovren parser model resume resume taxonomy
//
// swagger:model Sovren.Parser.Model.Resume.ResumeTaxonomy
type SovrenParserModelResumeResumeTaxonomy struct {

	// Id
	ID string `json:"Id,omitempty"`

	// name
	Name string `json:"Name,omitempty"`

	// percent of overall
	PercentOfOverall int32 `json:"PercentOfOverall,omitempty"`

	// sub taxonomies
	SubTaxonomies []*SovrenParserModelResumeResumeSubTaxonomy `json:"SubTaxonomies"`
}

// Validate validates this sovren parser model resume resume taxonomy
func (m *SovrenParserModelResumeResumeTaxonomy) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSubTaxonomies(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SovrenParserModelResumeResumeTaxonomy) validateSubTaxonomies(formats strfmt.Registry) error {
	if swag.IsZero(m.SubTaxonomies) { // not required
		return nil
	}

	for i := 0; i < len(m.SubTaxonomies); i++ {
		if swag.IsZero(m.SubTaxonomies[i]) { // not required
			continue
		}

		if m.SubTaxonomies[i] != nil {
			if err := m.SubTaxonomies[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("SubTaxonomies" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this sovren parser model resume resume taxonomy based on the context it is used
func (m *SovrenParserModelResumeResumeTaxonomy) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSubTaxonomies(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SovrenParserModelResumeResumeTaxonomy) contextValidateSubTaxonomies(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.SubTaxonomies); i++ {

		if m.SubTaxonomies[i] != nil {
			if err := m.SubTaxonomies[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("SubTaxonomies" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SovrenParserModelResumeResumeTaxonomy) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenParserModelResumeResumeTaxonomy) UnmarshalBinary(b []byte) error {
	var res SovrenParserModelResumeResumeTaxonomy
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
