// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenParserModelResumeWebAddress sovren parser model resume web address
//
// swagger:model Sovren.Parser.Model.Resume.WebAddress
type SovrenParserModelResumeWebAddress struct {

	// address
	Address string `json:"Address,omitempty"`

	// type
	Type string `json:"Type,omitempty"`
}

// Validate validates this sovren parser model resume web address
func (m *SovrenParserModelResumeWebAddress) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren parser model resume web address based on context it is used
func (m *SovrenParserModelResumeWebAddress) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenParserModelResumeWebAddress) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenParserModelResumeWebAddress) UnmarshalBinary(b []byte) error {
	var res SovrenParserModelResumeWebAddress
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
