// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenCategoryWeights sovren category weights
//
// swagger:model Sovren.CategoryWeights
type SovrenCategoryWeights struct {

	// certifications
	Certifications float64 `json:"Certifications,omitempty"`

	// education
	Education float64 `json:"Education,omitempty"`

	// executive type
	ExecutiveType float64 `json:"ExecutiveType,omitempty"`

	// industries
	Industries float64 `json:"Industries,omitempty"`

	// job titles
	JobTitles float64 `json:"JobTitles,omitempty"`

	// languages
	Languages float64 `json:"Languages,omitempty"`

	// management level
	ManagementLevel float64 `json:"ManagementLevel,omitempty"`

	// skills
	Skills float64 `json:"Skills,omitempty"`
}

// Validate validates this sovren category weights
func (m *SovrenCategoryWeights) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren category weights based on context it is used
func (m *SovrenCategoryWeights) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenCategoryWeights) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenCategoryWeights) UnmarshalBinary(b []byte) error {
	var res SovrenCategoryWeights
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
