// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenSaasDomainCreateNormalizationRequest sovren saas domain create normalization request
//
// swagger:model Sovren.Saas.Domain.CreateNormalizationRequest
type SovrenSaasDomainCreateNormalizationRequest struct {

	// content bytes
	// Format: byte
	ContentBytes strfmt.Base64 `json:"ContentBytes,omitempty"`

	// culture
	Culture string `json:"Culture,omitempty"`

	// name
	Name string `json:"Name,omitempty"`
}

// Validate validates this sovren saas domain create normalization request
func (m *SovrenSaasDomainCreateNormalizationRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren saas domain create normalization request based on context it is used
func (m *SovrenSaasDomainCreateNormalizationRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenSaasDomainCreateNormalizationRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenSaasDomainCreateNormalizationRequest) UnmarshalBinary(b []byte) error {
	var res SovrenSaasDomainCreateNormalizationRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
