// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SovrenParserModelSovrenDateWithParts sovren parser model sovren date with parts
//
// swagger:model Sovren.Parser.Model.SovrenDateWithParts
type SovrenParserModelSovrenDateWithParts struct {

	// date
	// Format: date
	Date strfmt.Date `json:"Date,omitempty"`

	// found day
	FoundDay bool `json:"FoundDay,omitempty"`

	// found month
	FoundMonth bool `json:"FoundMonth,omitempty"`

	// found year
	FoundYear bool `json:"FoundYear,omitempty"`

	// is current date
	IsCurrentDate bool `json:"IsCurrentDate,omitempty"`
}

// Validate validates this sovren parser model sovren date with parts
func (m *SovrenParserModelSovrenDateWithParts) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SovrenParserModelSovrenDateWithParts) validateDate(formats strfmt.Registry) error {
	if swag.IsZero(m.Date) { // not required
		return nil
	}

	if err := validate.FormatOf("Date", "body", "date", m.Date.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this sovren parser model sovren date with parts based on context it is used
func (m *SovrenParserModelSovrenDateWithParts) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenParserModelSovrenDateWithParts) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenParserModelSovrenDateWithParts) UnmarshalBinary(b []byte) error {
	var res SovrenParserModelSovrenDateWithParts
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
