// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenParserModelResumeFinding sovren parser model resume finding
//
// swagger:model Sovren.Parser.Model.Resume.Finding
type SovrenParserModelResumeFinding struct {

	// message
	Message string `json:"Message,omitempty"`

	// quality code
	QualityCode string `json:"QualityCode,omitempty"`

	// section identifiers
	SectionIdentifiers []*SovrenParserModelSectionIdentifier `json:"SectionIdentifiers"`
}

// Validate validates this sovren parser model resume finding
func (m *SovrenParserModelResumeFinding) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSectionIdentifiers(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SovrenParserModelResumeFinding) validateSectionIdentifiers(formats strfmt.Registry) error {
	if swag.IsZero(m.SectionIdentifiers) { // not required
		return nil
	}

	for i := 0; i < len(m.SectionIdentifiers); i++ {
		if swag.IsZero(m.SectionIdentifiers[i]) { // not required
			continue
		}

		if m.SectionIdentifiers[i] != nil {
			if err := m.SectionIdentifiers[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("SectionIdentifiers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this sovren parser model resume finding based on the context it is used
func (m *SovrenParserModelResumeFinding) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSectionIdentifiers(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SovrenParserModelResumeFinding) contextValidateSectionIdentifiers(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.SectionIdentifiers); i++ {

		if m.SectionIdentifiers[i] != nil {
			if err := m.SectionIdentifiers[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("SectionIdentifiers" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SovrenParserModelResumeFinding) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenParserModelResumeFinding) UnmarshalBinary(b []byte) error {
	var res SovrenParserModelResumeFinding
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
