// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenCategoryScoresJobTitlesCategoryScore sovren category scores job titles category score
//
// swagger:model Sovren.CategoryScores.JobTitlesCategoryScore
type SovrenCategoryScoresJobTitlesCategoryScore struct {

	// evidence
	Evidence []*SovrenCategoryScoresEvidence `json:"Evidence"`

	// found
	Found []*SovrenCategoryScoresJobTitleInfo `json:"Found"`

	// not found
	NotFound []string `json:"NotFound"`

	// unweighted score
	UnweightedScore float64 `json:"UnweightedScore,omitempty"`
}

// Validate validates this sovren category scores job titles category score
func (m *SovrenCategoryScoresJobTitlesCategoryScore) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEvidence(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFound(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SovrenCategoryScoresJobTitlesCategoryScore) validateEvidence(formats strfmt.Registry) error {
	if swag.IsZero(m.Evidence) { // not required
		return nil
	}

	for i := 0; i < len(m.Evidence); i++ {
		if swag.IsZero(m.Evidence[i]) { // not required
			continue
		}

		if m.Evidence[i] != nil {
			if err := m.Evidence[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Evidence" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *SovrenCategoryScoresJobTitlesCategoryScore) validateFound(formats strfmt.Registry) error {
	if swag.IsZero(m.Found) { // not required
		return nil
	}

	for i := 0; i < len(m.Found); i++ {
		if swag.IsZero(m.Found[i]) { // not required
			continue
		}

		if m.Found[i] != nil {
			if err := m.Found[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Found" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this sovren category scores job titles category score based on the context it is used
func (m *SovrenCategoryScoresJobTitlesCategoryScore) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateEvidence(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateFound(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SovrenCategoryScoresJobTitlesCategoryScore) contextValidateEvidence(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Evidence); i++ {

		if m.Evidence[i] != nil {
			if err := m.Evidence[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Evidence" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *SovrenCategoryScoresJobTitlesCategoryScore) contextValidateFound(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Found); i++ {

		if m.Found[i] != nil {
			if err := m.Found[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Found" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SovrenCategoryScoresJobTitlesCategoryScore) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenCategoryScoresJobTitlesCategoryScore) UnmarshalBinary(b []byte) error {
	var res SovrenCategoryScoresJobTitlesCategoryScore
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
