// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenParserModelResumeReservedData sovren parser model resume reserved data
//
// swagger:model Sovren.Parser.Model.Resume.ReservedData
type SovrenParserModelResumeReservedData struct {

	// email addresses
	EmailAddresses []string `json:"EmailAddresses"`

	// names
	Names []string `json:"Names"`

	// other data
	OtherData []string `json:"OtherData"`

	// phones
	Phones []string `json:"Phones"`

	// urls
	Urls []string `json:"Urls"`
}

// Validate validates this sovren parser model resume reserved data
func (m *SovrenParserModelResumeReservedData) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren parser model resume reserved data based on context it is used
func (m *SovrenParserModelResumeReservedData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenParserModelResumeReservedData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenParserModelResumeReservedData) UnmarshalBinary(b []byte) error {
	var res SovrenParserModelResumeReservedData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
