// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenSaasDomainParseJobOrderConfiguration sovren saas domain parse job order configuration
//
// swagger:model Sovren.Saas.Domain.ParseJobOrderConfiguration
type SovrenSaasDomainParseJobOrderConfiguration struct {

	// country code
	CountryCode string `json:"CountryCode,omitempty"`

	// include recruiting terms
	IncludeRecruitingTerms bool `json:"IncludeRecruitingTerms,omitempty"`

	// include supplemental text
	IncludeSupplementalText bool `json:"IncludeSupplementalText,omitempty"`

	// known type
	KnownType string `json:"KnownType,omitempty"`

	// language
	Language string `json:"Language,omitempty"`

	// prefer shorter job titles
	PreferShorterJobTitles bool `json:"PreferShorterJobTitles,omitempty"`
}

// Validate validates this sovren saas domain parse job order configuration
func (m *SovrenSaasDomainParseJobOrderConfiguration) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren saas domain parse job order configuration based on context it is used
func (m *SovrenSaasDomainParseJobOrderConfiguration) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenSaasDomainParseJobOrderConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenSaasDomainParseJobOrderConfiguration) UnmarshalBinary(b []byte) error {
	var res SovrenSaasDomainParseJobOrderConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
