// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenSaasDomainBulkDeleteRequestModel sovren saas domain bulk delete request model
//
// swagger:model Sovren.Saas.Domain.BulkDeleteRequestModel
type SovrenSaasDomainBulkDeleteRequestModel struct {

	// document ids
	DocumentIds []string `json:"DocumentIds"`
}

// Validate validates this sovren saas domain bulk delete request model
func (m *SovrenSaasDomainBulkDeleteRequestModel) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren saas domain bulk delete request model based on context it is used
func (m *SovrenSaasDomainBulkDeleteRequestModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenSaasDomainBulkDeleteRequestModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenSaasDomainBulkDeleteRequestModel) UnmarshalBinary(b []byte) error {
	var res SovrenSaasDomainBulkDeleteRequestModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
