// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenParserModelResumeLicenseDetail sovren parser model resume license detail
//
// swagger:model Sovren.Parser.Model.Resume.LicenseDetail
type SovrenParserModelResumeLicenseDetail struct {

	// matched from list
	MatchedFromList bool `json:"MatchedFromList,omitempty"`

	// name
	Name string `json:"Name,omitempty"`
}

// Validate validates this sovren parser model resume license detail
func (m *SovrenParserModelResumeLicenseDetail) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren parser model resume license detail based on context it is used
func (m *SovrenParserModelResumeLicenseDetail) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenParserModelResumeLicenseDetail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenParserModelResumeLicenseDetail) UnmarshalBinary(b []byte) error {
	var res SovrenParserModelResumeLicenseDetail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
