// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenParserModelResumeTelephone sovren parser model resume telephone
//
// swagger:model Sovren.Parser.Model.Resume.Telephone
type SovrenParserModelResumeTelephone struct {

	// area city code
	AreaCityCode string `json:"AreaCityCode,omitempty"`

	// international country code
	InternationalCountryCode string `json:"InternationalCountryCode,omitempty"`

	// normalized
	Normalized string `json:"Normalized,omitempty"`

	// raw
	Raw string `json:"Raw,omitempty"`

	// subscriber number
	SubscriberNumber string `json:"SubscriberNumber,omitempty"`
}

// Validate validates this sovren parser model resume telephone
func (m *SovrenParserModelResumeTelephone) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren parser model resume telephone based on context it is used
func (m *SovrenParserModelResumeTelephone) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenParserModelResumeTelephone) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenParserModelResumeTelephone) UnmarshalBinary(b []byte) error {
	var res SovrenParserModelResumeTelephone
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
