// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenParserModelJobJobSkill sovren parser model job job skill
//
// swagger:model Sovren.Parser.Model.Job.JobSkill
type SovrenParserModelJobJobSkill struct {

	// exists in text
	ExistsInText bool `json:"ExistsInText,omitempty"`

	// found in
	FoundIn []*SovrenParserModelSectionIdentifier `json:"FoundIn"`

	// Id
	ID string `json:"Id,omitempty"`

	// name
	Name string `json:"Name,omitempty"`

	// required
	Required bool `json:"Required,omitempty"`

	// variations
	Variations []*SovrenParserModelJobJobSkillVariation `json:"Variations"`
}

// Validate validates this sovren parser model job job skill
func (m *SovrenParserModelJobJobSkill) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFoundIn(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVariations(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SovrenParserModelJobJobSkill) validateFoundIn(formats strfmt.Registry) error {
	if swag.IsZero(m.FoundIn) { // not required
		return nil
	}

	for i := 0; i < len(m.FoundIn); i++ {
		if swag.IsZero(m.FoundIn[i]) { // not required
			continue
		}

		if m.FoundIn[i] != nil {
			if err := m.FoundIn[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("FoundIn" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *SovrenParserModelJobJobSkill) validateVariations(formats strfmt.Registry) error {
	if swag.IsZero(m.Variations) { // not required
		return nil
	}

	for i := 0; i < len(m.Variations); i++ {
		if swag.IsZero(m.Variations[i]) { // not required
			continue
		}

		if m.Variations[i] != nil {
			if err := m.Variations[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Variations" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this sovren parser model job job skill based on the context it is used
func (m *SovrenParserModelJobJobSkill) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFoundIn(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateVariations(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SovrenParserModelJobJobSkill) contextValidateFoundIn(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.FoundIn); i++ {

		if m.FoundIn[i] != nil {
			if err := m.FoundIn[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("FoundIn" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *SovrenParserModelJobJobSkill) contextValidateVariations(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Variations); i++ {

		if m.Variations[i] != nil {
			if err := m.Variations[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Variations" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SovrenParserModelJobJobSkill) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenParserModelJobJobSkill) UnmarshalBinary(b []byte) error {
	var res SovrenParserModelJobJobSkill
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
