// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenSaasDomainV10AddMultipleResumesToIndexRequestModel sovren saas domain v10 add multiple resumes to index request model
//
// swagger:model Sovren.Saas.Domain.V10.AddMultipleResumesToIndexRequestModel
type SovrenSaasDomainV10AddMultipleResumesToIndexRequestModel struct {

	// resumes
	Resumes []*SovrenIndexResumeRequest `json:"Resumes"`
}

// Validate validates this sovren saas domain v10 add multiple resumes to index request model
func (m *SovrenSaasDomainV10AddMultipleResumesToIndexRequestModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateResumes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SovrenSaasDomainV10AddMultipleResumesToIndexRequestModel) validateResumes(formats strfmt.Registry) error {
	if swag.IsZero(m.Resumes) { // not required
		return nil
	}

	for i := 0; i < len(m.Resumes); i++ {
		if swag.IsZero(m.Resumes[i]) { // not required
			continue
		}

		if m.Resumes[i] != nil {
			if err := m.Resumes[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Resumes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this sovren saas domain v10 add multiple resumes to index request model based on the context it is used
func (m *SovrenSaasDomainV10AddMultipleResumesToIndexRequestModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateResumes(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SovrenSaasDomainV10AddMultipleResumesToIndexRequestModel) contextValidateResumes(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Resumes); i++ {

		if m.Resumes[i] != nil {
			if err := m.Resumes[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Resumes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SovrenSaasDomainV10AddMultipleResumesToIndexRequestModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenSaasDomainV10AddMultipleResumesToIndexRequestModel) UnmarshalBinary(b []byte) error {
	var res SovrenSaasDomainV10AddMultipleResumesToIndexRequestModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
