// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenParserModelResumeExperienceSummary sovren parser model resume experience summary
//
// swagger:model Sovren.Parser.Model.Resume.ExperienceSummary
type SovrenParserModelResumeExperienceSummary struct {

	// attention needed
	AttentionNeeded string `json:"AttentionNeeded,omitempty"`

	// average months per employer
	AverageMonthsPerEmployer int32 `json:"AverageMonthsPerEmployer,omitempty"`

	// current management level
	CurrentManagementLevel string `json:"CurrentManagementLevel,omitempty"`

	// description
	Description string `json:"Description,omitempty"`

	// executive type
	ExecutiveType string `json:"ExecutiveType,omitempty"`

	// fulltime direct hire predictive index
	FulltimeDirectHirePredictiveIndex int32 `json:"FulltimeDirectHirePredictiveIndex,omitempty"`

	// management score
	ManagementScore int32 `json:"ManagementScore,omitempty"`

	// management story
	ManagementStory string `json:"ManagementStory,omitempty"`

	// months of management experience
	MonthsOfManagementExperience int32 `json:"MonthsOfManagementExperience,omitempty"`

	// months of work experience
	MonthsOfWorkExperience int32 `json:"MonthsOfWorkExperience,omitempty"`
}

// Validate validates this sovren parser model resume experience summary
func (m *SovrenParserModelResumeExperienceSummary) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren parser model resume experience summary based on context it is used
func (m *SovrenParserModelResumeExperienceSummary) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenParserModelResumeExperienceSummary) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenParserModelResumeExperienceSummary) UnmarshalBinary(b []byte) error {
	var res SovrenParserModelResumeExperienceSummary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
