// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenParserModelResumeJobTitle sovren parser model resume job title
//
// swagger:model Sovren.Parser.Model.Resume.JobTitle
type SovrenParserModelResumeJobTitle struct {

	// normalized
	Normalized string `json:"Normalized,omitempty"`

	// probability
	Probability string `json:"Probability,omitempty"`

	// raw
	Raw string `json:"Raw,omitempty"`

	// variations
	Variations []string `json:"Variations"`
}

// Validate validates this sovren parser model resume job title
func (m *SovrenParserModelResumeJobTitle) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren parser model resume job title based on context it is used
func (m *SovrenParserModelResumeJobTitle) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenParserModelResumeJobTitle) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenParserModelResumeJobTitle) UnmarshalBinary(b []byte) error {
	var res SovrenParserModelResumeJobTitle
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
