// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenBulkDocumentResponse sovren bulk document response
//
// swagger:model Sovren.BulkDocumentResponse
type SovrenBulkDocumentResponse struct {

	// code
	Code string `json:"Code,omitempty"`

	// document Id
	DocumentID string `json:"DocumentId,omitempty"`

	// message
	Message string `json:"Message,omitempty"`

	// sub code
	SubCode string `json:"SubCode,omitempty"`
}

// Validate validates this sovren bulk document response
func (m *SovrenBulkDocumentResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren bulk document response based on context it is used
func (m *SovrenBulkDocumentResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenBulkDocumentResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenBulkDocumentResponse) UnmarshalBinary(b []byte) error {
	var res SovrenBulkDocumentResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
