// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenSaasDomainV10GeocodeAndIndexResumeResponse sovren saas domain v10 geocode and index resume response
//
// swagger:model Sovren.Saas.Domain.V10.GeocodeAndIndexResumeResponse
type SovrenSaasDomainV10GeocodeAndIndexResumeResponse struct {

	// geocode response
	GeocodeResponse *SovrenSaasDomainResponseInfoModel `json:"GeocodeResponse,omitempty"`

	// indexing response
	IndexingResponse *SovrenSaasDomainResponseInfoModel `json:"IndexingResponse,omitempty"`

	// resume data
	ResumeData *SovrenParserModelResumeResumeData `json:"ResumeData,omitempty"`
}

// Validate validates this sovren saas domain v10 geocode and index resume response
func (m *SovrenSaasDomainV10GeocodeAndIndexResumeResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGeocodeResponse(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIndexingResponse(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResumeData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SovrenSaasDomainV10GeocodeAndIndexResumeResponse) validateGeocodeResponse(formats strfmt.Registry) error {
	if swag.IsZero(m.GeocodeResponse) { // not required
		return nil
	}

	if m.GeocodeResponse != nil {
		if err := m.GeocodeResponse.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("GeocodeResponse")
			}
			return err
		}
	}

	return nil
}

func (m *SovrenSaasDomainV10GeocodeAndIndexResumeResponse) validateIndexingResponse(formats strfmt.Registry) error {
	if swag.IsZero(m.IndexingResponse) { // not required
		return nil
	}

	if m.IndexingResponse != nil {
		if err := m.IndexingResponse.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("IndexingResponse")
			}
			return err
		}
	}

	return nil
}

func (m *SovrenSaasDomainV10GeocodeAndIndexResumeResponse) validateResumeData(formats strfmt.Registry) error {
	if swag.IsZero(m.ResumeData) { // not required
		return nil
	}

	if m.ResumeData != nil {
		if err := m.ResumeData.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ResumeData")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this sovren saas domain v10 geocode and index resume response based on the context it is used
func (m *SovrenSaasDomainV10GeocodeAndIndexResumeResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateGeocodeResponse(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateIndexingResponse(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateResumeData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SovrenSaasDomainV10GeocodeAndIndexResumeResponse) contextValidateGeocodeResponse(ctx context.Context, formats strfmt.Registry) error {

	if m.GeocodeResponse != nil {
		if err := m.GeocodeResponse.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("GeocodeResponse")
			}
			return err
		}
	}

	return nil
}

func (m *SovrenSaasDomainV10GeocodeAndIndexResumeResponse) contextValidateIndexingResponse(ctx context.Context, formats strfmt.Registry) error {

	if m.IndexingResponse != nil {
		if err := m.IndexingResponse.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("IndexingResponse")
			}
			return err
		}
	}

	return nil
}

func (m *SovrenSaasDomainV10GeocodeAndIndexResumeResponse) contextValidateResumeData(ctx context.Context, formats strfmt.Registry) error {

	if m.ResumeData != nil {
		if err := m.ResumeData.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ResumeData")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SovrenSaasDomainV10GeocodeAndIndexResumeResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenSaasDomainV10GeocodeAndIndexResumeResponse) UnmarshalBinary(b []byte) error {
	var res SovrenSaasDomainV10GeocodeAndIndexResumeResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
