// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenParserModelResumeCompanyName sovren parser model resume company name
//
// swagger:model Sovren.Parser.Model.Resume.CompanyName
type SovrenParserModelResumeCompanyName struct {

	// normalized
	Normalized string `json:"Normalized,omitempty"`

	// probability
	Probability string `json:"Probability,omitempty"`

	// raw
	Raw string `json:"Raw,omitempty"`
}

// Validate validates this sovren parser model resume company name
func (m *SovrenParserModelResumeCompanyName) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren parser model resume company name based on context it is used
func (m *SovrenParserModelResumeCompanyName) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenParserModelResumeCompanyName) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenParserModelResumeCompanyName) UnmarshalBinary(b []byte) error {
	var res SovrenParserModelResumeCompanyName
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
