// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenSaasDomainV10ResumeGeocoderResponseModel sovren saas domain v10 resume geocoder response model
//
// swagger:model Sovren.Saas.Domain.V10.ResumeGeocoderResponseModel
type SovrenSaasDomainV10ResumeGeocoderResponseModel struct {

	// resume data
	ResumeData *SovrenParserModelResumeResumeData `json:"ResumeData,omitempty"`
}

// Validate validates this sovren saas domain v10 resume geocoder response model
func (m *SovrenSaasDomainV10ResumeGeocoderResponseModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateResumeData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SovrenSaasDomainV10ResumeGeocoderResponseModel) validateResumeData(formats strfmt.Registry) error {
	if swag.IsZero(m.ResumeData) { // not required
		return nil
	}

	if m.ResumeData != nil {
		if err := m.ResumeData.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ResumeData")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this sovren saas domain v10 resume geocoder response model based on the context it is used
func (m *SovrenSaasDomainV10ResumeGeocoderResponseModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateResumeData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SovrenSaasDomainV10ResumeGeocoderResponseModel) contextValidateResumeData(ctx context.Context, formats strfmt.Registry) error {

	if m.ResumeData != nil {
		if err := m.ResumeData.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ResumeData")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SovrenSaasDomainV10ResumeGeocoderResponseModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenSaasDomainV10ResumeGeocoderResponseModel) UnmarshalBinary(b []byte) error {
	var res SovrenSaasDomainV10ResumeGeocoderResponseModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
