// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenParserModelResumeResumeSkillVariation sovren parser model resume resume skill variation
//
// swagger:model Sovren.Parser.Model.Resume.ResumeSkillVariation
type SovrenParserModelResumeResumeSkillVariation struct {

	// exists in text
	ExistsInText bool `json:"ExistsInText,omitempty"`

	// found in
	FoundIn []*SovrenParserModelSectionIdentifier `json:"FoundIn"`

	// Id
	ID string `json:"Id,omitempty"`

	// last used
	LastUsed *SovrenCommonV10ParserModelsSovrenPrimitive1SystemDateTimeMscorlibVersion4000CultureNeutralPublicKeyTokenB77a5c561934e089 `json:"LastUsed,omitempty"`

	// months experience
	MonthsExperience *SovrenCommonV10ParserModelsSovrenPrimitive1SystemInt32MscorlibVersion4000CultureNeutralPublicKeyTokenB77a5c561934e089 `json:"MonthsExperience,omitempty"`

	// name
	Name string `json:"Name,omitempty"`
}

// Validate validates this sovren parser model resume resume skill variation
func (m *SovrenParserModelResumeResumeSkillVariation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFoundIn(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLastUsed(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMonthsExperience(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SovrenParserModelResumeResumeSkillVariation) validateFoundIn(formats strfmt.Registry) error {
	if swag.IsZero(m.FoundIn) { // not required
		return nil
	}

	for i := 0; i < len(m.FoundIn); i++ {
		if swag.IsZero(m.FoundIn[i]) { // not required
			continue
		}

		if m.FoundIn[i] != nil {
			if err := m.FoundIn[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("FoundIn" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *SovrenParserModelResumeResumeSkillVariation) validateLastUsed(formats strfmt.Registry) error {
	if swag.IsZero(m.LastUsed) { // not required
		return nil
	}

	if m.LastUsed != nil {
		if err := m.LastUsed.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("LastUsed")
			}
			return err
		}
	}

	return nil
}

func (m *SovrenParserModelResumeResumeSkillVariation) validateMonthsExperience(formats strfmt.Registry) error {
	if swag.IsZero(m.MonthsExperience) { // not required
		return nil
	}

	if m.MonthsExperience != nil {
		if err := m.MonthsExperience.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("MonthsExperience")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this sovren parser model resume resume skill variation based on the context it is used
func (m *SovrenParserModelResumeResumeSkillVariation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateFoundIn(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLastUsed(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateMonthsExperience(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SovrenParserModelResumeResumeSkillVariation) contextValidateFoundIn(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.FoundIn); i++ {

		if m.FoundIn[i] != nil {
			if err := m.FoundIn[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("FoundIn" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *SovrenParserModelResumeResumeSkillVariation) contextValidateLastUsed(ctx context.Context, formats strfmt.Registry) error {

	if m.LastUsed != nil {
		if err := m.LastUsed.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("LastUsed")
			}
			return err
		}
	}

	return nil
}

func (m *SovrenParserModelResumeResumeSkillVariation) contextValidateMonthsExperience(ctx context.Context, formats strfmt.Registry) error {

	if m.MonthsExperience != nil {
		if err := m.MonthsExperience.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("MonthsExperience")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SovrenParserModelResumeResumeSkillVariation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenParserModelResumeResumeSkillVariation) UnmarshalBinary(b []byte) error {
	var res SovrenParserModelResumeResumeSkillVariation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
