// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenResumeBimetricMatchRequest sovren resume bimetric match request
//
// swagger:model Sovren.ResumeBimetricMatchRequest
type SovrenResumeBimetricMatchRequest struct {

	// preferred category weights
	PreferredCategoryWeights *SovrenCategoryWeights `json:"PreferredCategoryWeights,omitempty"`

	// settings
	Settings *SovrenMatchSettings `json:"Settings,omitempty"`

	// source resume
	SourceResume *SovrenV10ParsedResume `json:"SourceResume,omitempty"`

	// target jobs
	TargetJobs []*SovrenV10ParsedJob `json:"TargetJobs"`

	// target resumes
	TargetResumes []*SovrenV10ParsedResume `json:"TargetResumes"`
}

// Validate validates this sovren resume bimetric match request
func (m *SovrenResumeBimetricMatchRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePreferredCategoryWeights(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSettings(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSourceResume(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTargetJobs(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTargetResumes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SovrenResumeBimetricMatchRequest) validatePreferredCategoryWeights(formats strfmt.Registry) error {
	if swag.IsZero(m.PreferredCategoryWeights) { // not required
		return nil
	}

	if m.PreferredCategoryWeights != nil {
		if err := m.PreferredCategoryWeights.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("PreferredCategoryWeights")
			}
			return err
		}
	}

	return nil
}

func (m *SovrenResumeBimetricMatchRequest) validateSettings(formats strfmt.Registry) error {
	if swag.IsZero(m.Settings) { // not required
		return nil
	}

	if m.Settings != nil {
		if err := m.Settings.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Settings")
			}
			return err
		}
	}

	return nil
}

func (m *SovrenResumeBimetricMatchRequest) validateSourceResume(formats strfmt.Registry) error {
	if swag.IsZero(m.SourceResume) { // not required
		return nil
	}

	if m.SourceResume != nil {
		if err := m.SourceResume.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("SourceResume")
			}
			return err
		}
	}

	return nil
}

func (m *SovrenResumeBimetricMatchRequest) validateTargetJobs(formats strfmt.Registry) error {
	if swag.IsZero(m.TargetJobs) { // not required
		return nil
	}

	for i := 0; i < len(m.TargetJobs); i++ {
		if swag.IsZero(m.TargetJobs[i]) { // not required
			continue
		}

		if m.TargetJobs[i] != nil {
			if err := m.TargetJobs[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("TargetJobs" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *SovrenResumeBimetricMatchRequest) validateTargetResumes(formats strfmt.Registry) error {
	if swag.IsZero(m.TargetResumes) { // not required
		return nil
	}

	for i := 0; i < len(m.TargetResumes); i++ {
		if swag.IsZero(m.TargetResumes[i]) { // not required
			continue
		}

		if m.TargetResumes[i] != nil {
			if err := m.TargetResumes[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("TargetResumes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this sovren resume bimetric match request based on the context it is used
func (m *SovrenResumeBimetricMatchRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePreferredCategoryWeights(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSettings(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSourceResume(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTargetJobs(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTargetResumes(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SovrenResumeBimetricMatchRequest) contextValidatePreferredCategoryWeights(ctx context.Context, formats strfmt.Registry) error {

	if m.PreferredCategoryWeights != nil {
		if err := m.PreferredCategoryWeights.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("PreferredCategoryWeights")
			}
			return err
		}
	}

	return nil
}

func (m *SovrenResumeBimetricMatchRequest) contextValidateSettings(ctx context.Context, formats strfmt.Registry) error {

	if m.Settings != nil {
		if err := m.Settings.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Settings")
			}
			return err
		}
	}

	return nil
}

func (m *SovrenResumeBimetricMatchRequest) contextValidateSourceResume(ctx context.Context, formats strfmt.Registry) error {

	if m.SourceResume != nil {
		if err := m.SourceResume.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("SourceResume")
			}
			return err
		}
	}

	return nil
}

func (m *SovrenResumeBimetricMatchRequest) contextValidateTargetJobs(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.TargetJobs); i++ {

		if m.TargetJobs[i] != nil {
			if err := m.TargetJobs[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("TargetJobs" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *SovrenResumeBimetricMatchRequest) contextValidateTargetResumes(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.TargetResumes); i++ {

		if m.TargetResumes[i] != nil {
			if err := m.TargetResumes[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("TargetResumes" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SovrenResumeBimetricMatchRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenResumeBimetricMatchRequest) UnmarshalBinary(b []byte) error {
	var res SovrenResumeBimetricMatchRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
