// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenParserModelResumePersonName sovren parser model resume person name
//
// swagger:model Sovren.Parser.Model.Resume.PersonName
type SovrenParserModelResumePersonName struct {

	// family name
	FamilyName string `json:"FamilyName,omitempty"`

	// formatted name
	FormattedName string `json:"FormattedName,omitempty"`

	// given name
	GivenName string `json:"GivenName,omitempty"`

	// middle name
	MiddleName string `json:"MiddleName,omitempty"`

	// moniker
	Moniker string `json:"Moniker,omitempty"`

	// prefix
	Prefix string `json:"Prefix,omitempty"`

	// suffix
	Suffix string `json:"Suffix,omitempty"`
}

// Validate validates this sovren parser model resume person name
func (m *SovrenParserModelResumePersonName) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren parser model resume person name based on context it is used
func (m *SovrenParserModelResumePersonName) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenParserModelResumePersonName) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenParserModelResumePersonName) UnmarshalBinary(b []byte) error {
	var res SovrenParserModelResumePersonName
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
