// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenCategoryScore sovren category score
//
// swagger:model Sovren.CategoryScore
type SovrenCategoryScore struct {

	// category
	Category string `json:"Category,omitempty"`

	// terms found
	TermsFound []string `json:"TermsFound"`

	// unweighted score
	UnweightedScore float64 `json:"UnweightedScore,omitempty"`
}

// Validate validates this sovren category score
func (m *SovrenCategoryScore) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren category score based on context it is used
func (m *SovrenCategoryScore) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenCategoryScore) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenCategoryScore) UnmarshalBinary(b []byte) error {
	var res SovrenCategoryScore
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
