// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenGeoCoordinates sovren geo coordinates
//
// swagger:model Sovren.GeoCoordinates
type SovrenGeoCoordinates struct {

	// latitude
	Latitude float32 `json:"Latitude,omitempty"`

	// longitude
	Longitude float32 `json:"Longitude,omitempty"`
}

// Validate validates this sovren geo coordinates
func (m *SovrenGeoCoordinates) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren geo coordinates based on context it is used
func (m *SovrenGeoCoordinates) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenGeoCoordinates) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenGeoCoordinates) UnmarshalBinary(b []byte) error {
	var res SovrenGeoCoordinates
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
