// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenParserModelResumeSecurityCredential sovren parser model resume security credential
//
// swagger:model Sovren.Parser.Model.Resume.SecurityCredential
type SovrenParserModelResumeSecurityCredential struct {

	// found in context
	FoundInContext string `json:"FoundInContext,omitempty"`

	// name
	Name string `json:"Name,omitempty"`
}

// Validate validates this sovren parser model resume security credential
func (m *SovrenParserModelResumeSecurityCredential) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren parser model resume security credential based on context it is used
func (m *SovrenParserModelResumeSecurityCredential) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenParserModelResumeSecurityCredential) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenParserModelResumeSecurityCredential) UnmarshalBinary(b []byte) error {
	var res SovrenParserModelResumeSecurityCredential
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
