// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenSaasDomainV10Conversions sovren saas domain v10 conversions
//
// swagger:model Sovren.Saas.Domain.V10.Conversions
type SovrenSaasDomainV10Conversions struct {

	// candidate image
	// Format: byte
	CandidateImage strfmt.Base64 `json:"CandidateImage,omitempty"`

	// candidate image extension
	CandidateImageExtension string `json:"CandidateImageExtension,omitempty"`

	// HTML
	HTML string `json:"HTML,omitempty"`

	// p d f
	// Format: byte
	PDF strfmt.Base64 `json:"PDF,omitempty"`

	// r t f
	RTF string `json:"RTF,omitempty"`
}

// Validate validates this sovren saas domain v10 conversions
func (m *SovrenSaasDomainV10Conversions) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren saas domain v10 conversions based on context it is used
func (m *SovrenSaasDomainV10Conversions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenSaasDomainV10Conversions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenSaasDomainV10Conversions) UnmarshalBinary(b []byte) error {
	var res SovrenSaasDomainV10Conversions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
