// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenSaasDomainV10JobGeocoderResponseModel sovren saas domain v10 job geocoder response model
//
// swagger:model Sovren.Saas.Domain.V10.JobGeocoderResponseModel
type SovrenSaasDomainV10JobGeocoderResponseModel struct {

	// job data
	JobData *SovrenParserModelJobJobData `json:"JobData,omitempty"`
}

// Validate validates this sovren saas domain v10 job geocoder response model
func (m *SovrenSaasDomainV10JobGeocoderResponseModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateJobData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SovrenSaasDomainV10JobGeocoderResponseModel) validateJobData(formats strfmt.Registry) error {
	if swag.IsZero(m.JobData) { // not required
		return nil
	}

	if m.JobData != nil {
		if err := m.JobData.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("JobData")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this sovren saas domain v10 job geocoder response model based on the context it is used
func (m *SovrenSaasDomainV10JobGeocoderResponseModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateJobData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SovrenSaasDomainV10JobGeocoderResponseModel) contextValidateJobData(ctx context.Context, formats strfmt.Registry) error {

	if m.JobData != nil {
		if err := m.JobData.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("JobData")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SovrenSaasDomainV10JobGeocoderResponseModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenSaasDomainV10JobGeocoderResponseModel) UnmarshalBinary(b []byte) error {
	var res SovrenSaasDomainV10JobGeocoderResponseModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
