// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenSaasDomainV10GeocodeAndIndexJobRequest sovren saas domain v10 geocode and index job request
//
// swagger:model Sovren.Saas.Domain.V10.GeocodeAndIndexJobRequest
type SovrenSaasDomainV10GeocodeAndIndexJobRequest struct {

	// geocode options
	GeocodeOptions *SovrenGeoCodeOptionsBase `json:"GeocodeOptions,omitempty"`

	// index if geocode fails
	IndexIfGeocodeFails bool `json:"IndexIfGeocodeFails,omitempty"`

	// indexing options
	IndexingOptions *SovrenSaasDomainV10IndexingOptions `json:"IndexingOptions,omitempty"`

	// job data
	JobData *SovrenParserModelJobJobData `json:"JobData,omitempty"`
}

// Validate validates this sovren saas domain v10 geocode and index job request
func (m *SovrenSaasDomainV10GeocodeAndIndexJobRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGeocodeOptions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIndexingOptions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateJobData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SovrenSaasDomainV10GeocodeAndIndexJobRequest) validateGeocodeOptions(formats strfmt.Registry) error {
	if swag.IsZero(m.GeocodeOptions) { // not required
		return nil
	}

	if m.GeocodeOptions != nil {
		if err := m.GeocodeOptions.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("GeocodeOptions")
			}
			return err
		}
	}

	return nil
}

func (m *SovrenSaasDomainV10GeocodeAndIndexJobRequest) validateIndexingOptions(formats strfmt.Registry) error {
	if swag.IsZero(m.IndexingOptions) { // not required
		return nil
	}

	if m.IndexingOptions != nil {
		if err := m.IndexingOptions.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("IndexingOptions")
			}
			return err
		}
	}

	return nil
}

func (m *SovrenSaasDomainV10GeocodeAndIndexJobRequest) validateJobData(formats strfmt.Registry) error {
	if swag.IsZero(m.JobData) { // not required
		return nil
	}

	if m.JobData != nil {
		if err := m.JobData.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("JobData")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this sovren saas domain v10 geocode and index job request based on the context it is used
func (m *SovrenSaasDomainV10GeocodeAndIndexJobRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateGeocodeOptions(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateIndexingOptions(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateJobData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SovrenSaasDomainV10GeocodeAndIndexJobRequest) contextValidateGeocodeOptions(ctx context.Context, formats strfmt.Registry) error {

	if m.GeocodeOptions != nil {
		if err := m.GeocodeOptions.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("GeocodeOptions")
			}
			return err
		}
	}

	return nil
}

func (m *SovrenSaasDomainV10GeocodeAndIndexJobRequest) contextValidateIndexingOptions(ctx context.Context, formats strfmt.Registry) error {

	if m.IndexingOptions != nil {
		if err := m.IndexingOptions.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("IndexingOptions")
			}
			return err
		}
	}

	return nil
}

func (m *SovrenSaasDomainV10GeocodeAndIndexJobRequest) contextValidateJobData(ctx context.Context, formats strfmt.Registry) error {

	if m.JobData != nil {
		if err := m.JobData.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("JobData")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SovrenSaasDomainV10GeocodeAndIndexJobRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenSaasDomainV10GeocodeAndIndexJobRequest) UnmarshalBinary(b []byte) error {
	var res SovrenSaasDomainV10GeocodeAndIndexJobRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
