// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SovrenSaasDomainV10ResponseInfoModel sovren saas domain v10 response info model
//
// swagger:model Sovren.Saas.Domain.V10ResponseInfoModel
type SovrenSaasDomainV10ResponseInfoModel struct {

	// Api version
	APIVersion string `json:"ApiVersion,omitempty"`

	// code
	// Enum: [Success SomeErrors MissingParameter InvalidParameter InsufficientData AuthenticationError Unauthorized DataNotFound CoordinatesNotFound UnhandledException ConversionException PossibleTruncationFromTimeout WarningsFoundDuringParsing ConstraintError DuplicateAsset UnsupportedContentTypeHeader InstallationError TooManyRequests MaintenanceMode Conflict]
	Code string `json:"Code,omitempty"`

	// customer details
	CustomerDetails *SovrenSaasDomainV10CustomerDetails `json:"CustomerDetails,omitempty"`

	// engine version
	EngineVersion string `json:"EngineVersion,omitempty"`

	// message
	Message string `json:"Message,omitempty"`

	// total elapsed milliseconds
	TotalElapsedMilliseconds int64 `json:"TotalElapsedMilliseconds,omitempty"`

	// transaction Id
	TransactionID string `json:"TransactionId,omitempty"`
}

// Validate validates this sovren saas domain v10 response info model
func (m *SovrenSaasDomainV10ResponseInfoModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCode(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCustomerDetails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var sovrenSaasDomainV10ResponseInfoModelTypeCodePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Success","SomeErrors","MissingParameter","InvalidParameter","InsufficientData","AuthenticationError","Unauthorized","DataNotFound","CoordinatesNotFound","UnhandledException","ConversionException","PossibleTruncationFromTimeout","WarningsFoundDuringParsing","ConstraintError","DuplicateAsset","UnsupportedContentTypeHeader","InstallationError","TooManyRequests","MaintenanceMode","Conflict"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		sovrenSaasDomainV10ResponseInfoModelTypeCodePropEnum = append(sovrenSaasDomainV10ResponseInfoModelTypeCodePropEnum, v)
	}
}

const (

	// SovrenSaasDomainV10ResponseInfoModelCodeSuccess captures enum value "Success"
	SovrenSaasDomainV10ResponseInfoModelCodeSuccess string = "Success"

	// SovrenSaasDomainV10ResponseInfoModelCodeSomeErrors captures enum value "SomeErrors"
	SovrenSaasDomainV10ResponseInfoModelCodeSomeErrors string = "SomeErrors"

	// SovrenSaasDomainV10ResponseInfoModelCodeMissingParameter captures enum value "MissingParameter"
	SovrenSaasDomainV10ResponseInfoModelCodeMissingParameter string = "MissingParameter"

	// SovrenSaasDomainV10ResponseInfoModelCodeInvalidParameter captures enum value "InvalidParameter"
	SovrenSaasDomainV10ResponseInfoModelCodeInvalidParameter string = "InvalidParameter"

	// SovrenSaasDomainV10ResponseInfoModelCodeInsufficientData captures enum value "InsufficientData"
	SovrenSaasDomainV10ResponseInfoModelCodeInsufficientData string = "InsufficientData"

	// SovrenSaasDomainV10ResponseInfoModelCodeAuthenticationError captures enum value "AuthenticationError"
	SovrenSaasDomainV10ResponseInfoModelCodeAuthenticationError string = "AuthenticationError"

	// SovrenSaasDomainV10ResponseInfoModelCodeUnauthorized captures enum value "Unauthorized"
	SovrenSaasDomainV10ResponseInfoModelCodeUnauthorized string = "Unauthorized"

	// SovrenSaasDomainV10ResponseInfoModelCodeDataNotFound captures enum value "DataNotFound"
	SovrenSaasDomainV10ResponseInfoModelCodeDataNotFound string = "DataNotFound"

	// SovrenSaasDomainV10ResponseInfoModelCodeCoordinatesNotFound captures enum value "CoordinatesNotFound"
	SovrenSaasDomainV10ResponseInfoModelCodeCoordinatesNotFound string = "CoordinatesNotFound"

	// SovrenSaasDomainV10ResponseInfoModelCodeUnhandledException captures enum value "UnhandledException"
	SovrenSaasDomainV10ResponseInfoModelCodeUnhandledException string = "UnhandledException"

	// SovrenSaasDomainV10ResponseInfoModelCodeConversionException captures enum value "ConversionException"
	SovrenSaasDomainV10ResponseInfoModelCodeConversionException string = "ConversionException"

	// SovrenSaasDomainV10ResponseInfoModelCodePossibleTruncationFromTimeout captures enum value "PossibleTruncationFromTimeout"
	SovrenSaasDomainV10ResponseInfoModelCodePossibleTruncationFromTimeout string = "PossibleTruncationFromTimeout"

	// SovrenSaasDomainV10ResponseInfoModelCodeWarningsFoundDuringParsing captures enum value "WarningsFoundDuringParsing"
	SovrenSaasDomainV10ResponseInfoModelCodeWarningsFoundDuringParsing string = "WarningsFoundDuringParsing"

	// SovrenSaasDomainV10ResponseInfoModelCodeConstraintError captures enum value "ConstraintError"
	SovrenSaasDomainV10ResponseInfoModelCodeConstraintError string = "ConstraintError"

	// SovrenSaasDomainV10ResponseInfoModelCodeDuplicateAsset captures enum value "DuplicateAsset"
	SovrenSaasDomainV10ResponseInfoModelCodeDuplicateAsset string = "DuplicateAsset"

	// SovrenSaasDomainV10ResponseInfoModelCodeUnsupportedContentTypeHeader captures enum value "UnsupportedContentTypeHeader"
	SovrenSaasDomainV10ResponseInfoModelCodeUnsupportedContentTypeHeader string = "UnsupportedContentTypeHeader"

	// SovrenSaasDomainV10ResponseInfoModelCodeInstallationError captures enum value "InstallationError"
	SovrenSaasDomainV10ResponseInfoModelCodeInstallationError string = "InstallationError"

	// SovrenSaasDomainV10ResponseInfoModelCodeTooManyRequests captures enum value "TooManyRequests"
	SovrenSaasDomainV10ResponseInfoModelCodeTooManyRequests string = "TooManyRequests"

	// SovrenSaasDomainV10ResponseInfoModelCodeMaintenanceMode captures enum value "MaintenanceMode"
	SovrenSaasDomainV10ResponseInfoModelCodeMaintenanceMode string = "MaintenanceMode"

	// SovrenSaasDomainV10ResponseInfoModelCodeConflict captures enum value "Conflict"
	SovrenSaasDomainV10ResponseInfoModelCodeConflict string = "Conflict"
)

// prop value enum
func (m *SovrenSaasDomainV10ResponseInfoModel) validateCodeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, sovrenSaasDomainV10ResponseInfoModelTypeCodePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *SovrenSaasDomainV10ResponseInfoModel) validateCode(formats strfmt.Registry) error {
	if swag.IsZero(m.Code) { // not required
		return nil
	}

	// value enum
	if err := m.validateCodeEnum("Code", "body", m.Code); err != nil {
		return err
	}

	return nil
}

func (m *SovrenSaasDomainV10ResponseInfoModel) validateCustomerDetails(formats strfmt.Registry) error {
	if swag.IsZero(m.CustomerDetails) { // not required
		return nil
	}

	if m.CustomerDetails != nil {
		if err := m.CustomerDetails.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("CustomerDetails")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this sovren saas domain v10 response info model based on the context it is used
func (m *SovrenSaasDomainV10ResponseInfoModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCustomerDetails(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SovrenSaasDomainV10ResponseInfoModel) contextValidateCustomerDetails(ctx context.Context, formats strfmt.Registry) error {

	if m.CustomerDetails != nil {
		if err := m.CustomerDetails.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("CustomerDetails")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SovrenSaasDomainV10ResponseInfoModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenSaasDomainV10ResponseInfoModel) UnmarshalBinary(b []byte) error {
	var res SovrenSaasDomainV10ResponseInfoModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
