// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenParserModelResumeResumeSection sovren parser model resume resume section
//
// swagger:model Sovren.Parser.Model.Resume.ResumeSection
type SovrenParserModelResumeResumeSection struct {

	// first line number
	FirstLineNumber int32 `json:"FirstLineNumber,omitempty"`

	// header text found
	HeaderTextFound string `json:"HeaderTextFound,omitempty"`

	// last line number
	LastLineNumber int32 `json:"LastLineNumber,omitempty"`

	// section type
	SectionType string `json:"SectionType,omitempty"`
}

// Validate validates this sovren parser model resume resume section
func (m *SovrenParserModelResumeResumeSection) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren parser model resume resume section based on context it is used
func (m *SovrenParserModelResumeResumeSection) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenParserModelResumeResumeSection) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenParserModelResumeResumeSection) UnmarshalBinary(b []byte) error {
	var res SovrenParserModelResumeResumeSection
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
