// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenCategoryScoresSkillInfo sovren category scores skill info
//
// swagger:model Sovren.CategoryScores.SkillInfo
type SovrenCategoryScoresSkillInfo struct {

	// is current
	IsCurrent bool `json:"IsCurrent,omitempty"`

	// skill
	Skill string `json:"Skill,omitempty"`
}

// Validate validates this sovren category scores skill info
func (m *SovrenCategoryScoresSkillInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren category scores skill info based on context it is used
func (m *SovrenCategoryScoresSkillInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenCategoryScoresSkillInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenCategoryScoresSkillInfo) UnmarshalBinary(b []byte) error {
	var res SovrenCategoryScoresSkillInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
