// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SovrenV10UpdateDocumentCustomValuesRequest sovren v10 update document custom values request
//
// swagger:model Sovren.V10UpdateDocumentCustomValuesRequest
type SovrenV10UpdateDocumentCustomValuesRequest struct {

	// method
	// Enum: [Overwrite Add Delete]
	Method string `json:"Method,omitempty"`

	// user defined tags
	UserDefinedTags []string `json:"UserDefinedTags"`
}

// Validate validates this sovren v10 update document custom values request
func (m *SovrenV10UpdateDocumentCustomValuesRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMethod(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var sovrenV10UpdateDocumentCustomValuesRequestTypeMethodPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Overwrite","Add","Delete"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		sovrenV10UpdateDocumentCustomValuesRequestTypeMethodPropEnum = append(sovrenV10UpdateDocumentCustomValuesRequestTypeMethodPropEnum, v)
	}
}

const (

	// SovrenV10UpdateDocumentCustomValuesRequestMethodOverwrite captures enum value "Overwrite"
	SovrenV10UpdateDocumentCustomValuesRequestMethodOverwrite string = "Overwrite"

	// SovrenV10UpdateDocumentCustomValuesRequestMethodAdd captures enum value "Add"
	SovrenV10UpdateDocumentCustomValuesRequestMethodAdd string = "Add"

	// SovrenV10UpdateDocumentCustomValuesRequestMethodDelete captures enum value "Delete"
	SovrenV10UpdateDocumentCustomValuesRequestMethodDelete string = "Delete"
)

// prop value enum
func (m *SovrenV10UpdateDocumentCustomValuesRequest) validateMethodEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, sovrenV10UpdateDocumentCustomValuesRequestTypeMethodPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *SovrenV10UpdateDocumentCustomValuesRequest) validateMethod(formats strfmt.Registry) error {
	if swag.IsZero(m.Method) { // not required
		return nil
	}

	// value enum
	if err := m.validateMethodEnum("Method", "body", m.Method); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this sovren v10 update document custom values request based on context it is used
func (m *SovrenV10UpdateDocumentCustomValuesRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenV10UpdateDocumentCustomValuesRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenV10UpdateDocumentCustomValuesRequest) UnmarshalBinary(b []byte) error {
	var res SovrenV10UpdateDocumentCustomValuesRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
