// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenParserModelResumeEmploymentHistory sovren parser model resume employment history
//
// swagger:model Sovren.Parser.Model.Resume.EmploymentHistory
type SovrenParserModelResumeEmploymentHistory struct {

	// experience summary
	ExperienceSummary *SovrenParserModelResumeExperienceSummary `json:"ExperienceSummary,omitempty"`

	// positions
	Positions []*SovrenParserModelResumePosition `json:"Positions"`
}

// Validate validates this sovren parser model resume employment history
func (m *SovrenParserModelResumeEmploymentHistory) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExperienceSummary(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePositions(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SovrenParserModelResumeEmploymentHistory) validateExperienceSummary(formats strfmt.Registry) error {
	if swag.IsZero(m.ExperienceSummary) { // not required
		return nil
	}

	if m.ExperienceSummary != nil {
		if err := m.ExperienceSummary.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ExperienceSummary")
			}
			return err
		}
	}

	return nil
}

func (m *SovrenParserModelResumeEmploymentHistory) validatePositions(formats strfmt.Registry) error {
	if swag.IsZero(m.Positions) { // not required
		return nil
	}

	for i := 0; i < len(m.Positions); i++ {
		if swag.IsZero(m.Positions[i]) { // not required
			continue
		}

		if m.Positions[i] != nil {
			if err := m.Positions[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Positions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this sovren parser model resume employment history based on the context it is used
func (m *SovrenParserModelResumeEmploymentHistory) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateExperienceSummary(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePositions(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SovrenParserModelResumeEmploymentHistory) contextValidateExperienceSummary(ctx context.Context, formats strfmt.Registry) error {

	if m.ExperienceSummary != nil {
		if err := m.ExperienceSummary.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ExperienceSummary")
			}
			return err
		}
	}

	return nil
}

func (m *SovrenParserModelResumeEmploymentHistory) contextValidatePositions(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Positions); i++ {

		if m.Positions[i] != nil {
			if err := m.Positions[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("Positions" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SovrenParserModelResumeEmploymentHistory) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenParserModelResumeEmploymentHistory) UnmarshalBinary(b []byte) error {
	var res SovrenParserModelResumeEmploymentHistory
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
