// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SovrenSaasDomainCreateIndexRequestModel sovren saas domain create index request model
//
// swagger:model Sovren.Saas.Domain.CreateIndexRequestModel
type SovrenSaasDomainCreateIndexRequestModel struct {

	// index type
	// Enum: [Resume Job]
	IndexType string `json:"IndexType,omitempty"`
}

// Validate validates this sovren saas domain create index request model
func (m *SovrenSaasDomainCreateIndexRequestModel) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIndexType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var sovrenSaasDomainCreateIndexRequestModelTypeIndexTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Resume","Job"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		sovrenSaasDomainCreateIndexRequestModelTypeIndexTypePropEnum = append(sovrenSaasDomainCreateIndexRequestModelTypeIndexTypePropEnum, v)
	}
}

const (

	// SovrenSaasDomainCreateIndexRequestModelIndexTypeResume captures enum value "Resume"
	SovrenSaasDomainCreateIndexRequestModelIndexTypeResume string = "Resume"

	// SovrenSaasDomainCreateIndexRequestModelIndexTypeJob captures enum value "Job"
	SovrenSaasDomainCreateIndexRequestModelIndexTypeJob string = "Job"
)

// prop value enum
func (m *SovrenSaasDomainCreateIndexRequestModel) validateIndexTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, sovrenSaasDomainCreateIndexRequestModelTypeIndexTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *SovrenSaasDomainCreateIndexRequestModel) validateIndexType(formats strfmt.Registry) error {
	if swag.IsZero(m.IndexType) { // not required
		return nil
	}

	// value enum
	if err := m.validateIndexTypeEnum("IndexType", "body", m.IndexType); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this sovren saas domain create index request model based on context it is used
func (m *SovrenSaasDomainCreateIndexRequestModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenSaasDomainCreateIndexRequestModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenSaasDomainCreateIndexRequestModel) UnmarshalBinary(b []byte) error {
	var res SovrenSaasDomainCreateIndexRequestModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
