// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenEducation sovren education
//
// swagger:model Sovren.Education
type SovrenEducation struct {

	// degree major
	DegreeMajor string `json:"DegreeMajor,omitempty"`

	// degree name
	DegreeName string `json:"DegreeName,omitempty"`

	// degree type
	DegreeType string `json:"DegreeType,omitempty"`

	// minimum g p a
	MinimumGPA float64 `json:"MinimumGPA,omitempty"`

	// school name
	SchoolName string `json:"SchoolName,omitempty"`
}

// Validate validates this sovren education
func (m *SovrenEducation) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren education based on context it is used
func (m *SovrenEducation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenEducation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenEducation) UnmarshalBinary(b []byte) error {
	var res SovrenEducation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
