// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenJobTitleSlim sovren job title slim
//
// swagger:model Sovren.JobTitleSlim
type SovrenJobTitleSlim struct {

	// is current
	IsCurrent bool `json:"IsCurrent,omitempty"`

	// title
	Title string `json:"Title,omitempty"`
}

// Validate validates this sovren job title slim
func (m *SovrenJobTitleSlim) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren job title slim based on context it is used
func (m *SovrenJobTitleSlim) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenJobTitleSlim) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenJobTitleSlim) UnmarshalBinary(b []byte) error {
	var res SovrenJobTitleSlim
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
