// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenParserModelResumeNationalIdentity sovren parser model resume national identity
//
// swagger:model Sovren.Parser.Model.Resume.NationalIdentity
type SovrenParserModelResumeNationalIdentity struct {

	// number
	Number string `json:"Number,omitempty"`

	// phrase
	Phrase string `json:"Phrase,omitempty"`
}

// Validate validates this sovren parser model resume national identity
func (m *SovrenParserModelResumeNationalIdentity) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren parser model resume national identity based on context it is used
func (m *SovrenParserModelResumeNationalIdentity) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenParserModelResumeNationalIdentity) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenParserModelResumeNationalIdentity) UnmarshalBinary(b []byte) error {
	var res SovrenParserModelResumeNationalIdentity
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
