// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenParserModelSovrenLocation sovren parser model sovren location
//
// swagger:model Sovren.Parser.Model.SovrenLocation
type SovrenParserModelSovrenLocation struct {

	// country code
	CountryCode string `json:"CountryCode,omitempty"`

	// geo coordinates
	GeoCoordinates *SovrenParserModelGeoCoordinate `json:"GeoCoordinates,omitempty"`

	// municipality
	Municipality string `json:"Municipality,omitempty"`

	// postal code
	PostalCode string `json:"PostalCode,omitempty"`

	// regions
	Regions []string `json:"Regions"`

	// street address lines
	StreetAddressLines []string `json:"StreetAddressLines"`
}

// Validate validates this sovren parser model sovren location
func (m *SovrenParserModelSovrenLocation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGeoCoordinates(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SovrenParserModelSovrenLocation) validateGeoCoordinates(formats strfmt.Registry) error {
	if swag.IsZero(m.GeoCoordinates) { // not required
		return nil
	}

	if m.GeoCoordinates != nil {
		if err := m.GeoCoordinates.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("GeoCoordinates")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this sovren parser model sovren location based on the context it is used
func (m *SovrenParserModelSovrenLocation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateGeoCoordinates(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SovrenParserModelSovrenLocation) contextValidateGeoCoordinates(ctx context.Context, formats strfmt.Registry) error {

	if m.GeoCoordinates != nil {
		if err := m.GeoCoordinates.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("GeoCoordinates")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SovrenParserModelSovrenLocation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenParserModelSovrenLocation) UnmarshalBinary(b []byte) error {
	var res SovrenParserModelSovrenLocation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
