// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenCategoryScoresTaxonomyEvidence sovren category scores taxonomy evidence
//
// swagger:model Sovren.CategoryScores.TaxonomyEvidence
type SovrenCategoryScoresTaxonomyEvidence struct {

	// primary
	Primary *SovrenCategoryScoresTaxonomyInfo `json:"Primary,omitempty"`

	// secondary
	Secondary *SovrenCategoryScoresTaxonomyInfo `json:"Secondary,omitempty"`
}

// Validate validates this sovren category scores taxonomy evidence
func (m *SovrenCategoryScoresTaxonomyEvidence) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePrimary(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSecondary(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SovrenCategoryScoresTaxonomyEvidence) validatePrimary(formats strfmt.Registry) error {
	if swag.IsZero(m.Primary) { // not required
		return nil
	}

	if m.Primary != nil {
		if err := m.Primary.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Primary")
			}
			return err
		}
	}

	return nil
}

func (m *SovrenCategoryScoresTaxonomyEvidence) validateSecondary(formats strfmt.Registry) error {
	if swag.IsZero(m.Secondary) { // not required
		return nil
	}

	if m.Secondary != nil {
		if err := m.Secondary.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Secondary")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this sovren category scores taxonomy evidence based on the context it is used
func (m *SovrenCategoryScoresTaxonomyEvidence) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePrimary(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSecondary(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SovrenCategoryScoresTaxonomyEvidence) contextValidatePrimary(ctx context.Context, formats strfmt.Registry) error {

	if m.Primary != nil {
		if err := m.Primary.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Primary")
			}
			return err
		}
	}

	return nil
}

func (m *SovrenCategoryScoresTaxonomyEvidence) contextValidateSecondary(ctx context.Context, formats strfmt.Registry) error {

	if m.Secondary != nil {
		if err := m.Secondary.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("Secondary")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *SovrenCategoryScoresTaxonomyEvidence) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenCategoryScoresTaxonomyEvidence) UnmarshalBinary(b []byte) error {
	var res SovrenCategoryScoresTaxonomyEvidence
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
