// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SovrenSaasDomainV10CustomerDetails sovren saas domain v10 customer details
//
// swagger:model Sovren.Saas.Domain.V10.CustomerDetails
type SovrenSaasDomainV10CustomerDetails struct {

	// account Id
	AccountID string `json:"AccountId,omitempty"`

	// credits remaining
	CreditsRemaining float64 `json:"CreditsRemaining,omitempty"`

	// credits used
	CreditsUsed int32 `json:"CreditsUsed,omitempty"`

	// expiration date
	// Format: date
	ExpirationDate strfmt.Date `json:"ExpirationDate,omitempty"`

	// IP address
	IPAddress string `json:"IPAddress,omitempty"`

	// maximum concurrent requests
	MaximumConcurrentRequests int32 `json:"MaximumConcurrentRequests,omitempty"`

	// name
	Name string `json:"Name,omitempty"`

	// region
	Region string `json:"Region,omitempty"`
}

// Validate validates this sovren saas domain v10 customer details
func (m *SovrenSaasDomainV10CustomerDetails) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExpirationDate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SovrenSaasDomainV10CustomerDetails) validateExpirationDate(formats strfmt.Registry) error {
	if swag.IsZero(m.ExpirationDate) { // not required
		return nil
	}

	if err := validate.FormatOf("ExpirationDate", "body", "date", m.ExpirationDate.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this sovren saas domain v10 customer details based on context it is used
func (m *SovrenSaasDomainV10CustomerDetails) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenSaasDomainV10CustomerDetails) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenSaasDomainV10CustomerDetails) UnmarshalBinary(b []byte) error {
	var res SovrenSaasDomainV10CustomerDetails
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
