// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenPaginationSettings sovren pagination settings
//
// swagger:model Sovren.PaginationSettings
type SovrenPaginationSettings struct {

	// skip
	Skip int32 `json:"Skip,omitempty"`

	// take
	Take int32 `json:"Take,omitempty"`
}

// Validate validates this sovren pagination settings
func (m *SovrenPaginationSettings) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren pagination settings based on context it is used
func (m *SovrenPaginationSettings) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenPaginationSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenPaginationSettings) UnmarshalBinary(b []byte) error {
	var res SovrenPaginationSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
