// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenParserModelResumeGradepointAverage sovren parser model resume gradepoint average
//
// swagger:model Sovren.Parser.Model.Resume.GradepointAverage
type SovrenParserModelResumeGradepointAverage struct {

	// max score
	MaxScore string `json:"MaxScore,omitempty"`

	// minimum score
	MinimumScore string `json:"MinimumScore,omitempty"`

	// normalized score
	NormalizedScore float64 `json:"NormalizedScore,omitempty"`

	// score
	Score string `json:"Score,omitempty"`

	// scoring system
	ScoringSystem string `json:"ScoringSystem,omitempty"`
}

// Validate validates this sovren parser model resume gradepoint average
func (m *SovrenParserModelResumeGradepointAverage) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren parser model resume gradepoint average based on context it is used
func (m *SovrenParserModelResumeGradepointAverage) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenParserModelResumeGradepointAverage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenParserModelResumeGradepointAverage) UnmarshalBinary(b []byte) error {
	var res SovrenParserModelResumeGradepointAverage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
