// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenParserModelResumeLanguageCompetency sovren parser model resume language competency
//
// swagger:model Sovren.Parser.Model.Resume.LanguageCompetency
type SovrenParserModelResumeLanguageCompetency struct {

	// found in context
	FoundInContext string `json:"FoundInContext,omitempty"`

	// language
	Language string `json:"Language,omitempty"`

	// language code
	LanguageCode string `json:"LanguageCode,omitempty"`
}

// Validate validates this sovren parser model resume language competency
func (m *SovrenParserModelResumeLanguageCompetency) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren parser model resume language competency based on context it is used
func (m *SovrenParserModelResumeLanguageCompetency) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenParserModelResumeLanguageCompetency) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenParserModelResumeLanguageCompetency) UnmarshalBinary(b []byte) error {
	var res SovrenParserModelResumeLanguageCompetency
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
