// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenCategoryScoresTaxonomyMatchInfo sovren category scores taxonomy match info
//
// swagger:model Sovren.CategoryScores.TaxonomyMatchInfo
type SovrenCategoryScoresTaxonomyMatchInfo struct {

	// Id
	ID string `json:"Id,omitempty"`

	// matched
	Matched bool `json:"Matched,omitempty"`

	// name
	Name string `json:"Name,omitempty"`
}

// Validate validates this sovren category scores taxonomy match info
func (m *SovrenCategoryScoresTaxonomyMatchInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren category scores taxonomy match info based on context it is used
func (m *SovrenCategoryScoresTaxonomyMatchInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenCategoryScoresTaxonomyMatchInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenCategoryScoresTaxonomyMatchInfo) UnmarshalBinary(b []byte) error {
	var res SovrenCategoryScoresTaxonomyMatchInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
