// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenParserModelGeoCoordinate sovren parser model geo coordinate
//
// swagger:model Sovren.Parser.Model.GeoCoordinate
type SovrenParserModelGeoCoordinate struct {

	// latitude
	Latitude float64 `json:"Latitude,omitempty"`

	// longitude
	Longitude float64 `json:"Longitude,omitempty"`

	// source
	Source string `json:"Source,omitempty"`
}

// Validate validates this sovren parser model geo coordinate
func (m *SovrenParserModelGeoCoordinate) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren parser model geo coordinate based on context it is used
func (m *SovrenParserModelGeoCoordinate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenParserModelGeoCoordinate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenParserModelGeoCoordinate) UnmarshalBinary(b []byte) error {
	var res SovrenParserModelGeoCoordinate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
