// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenParserModelJobJobTitles sovren parser model job job titles
//
// swagger:model Sovren.Parser.Model.Job.JobTitles
type SovrenParserModelJobJobTitles struct {

	// job title
	JobTitle []string `json:"JobTitle"`

	// main job title
	MainJobTitle string `json:"MainJobTitle,omitempty"`
}

// Validate validates this sovren parser model job job titles
func (m *SovrenParserModelJobJobTitles) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren parser model job job titles based on context it is used
func (m *SovrenParserModelJobJobTitles) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenParserModelJobJobTitles) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenParserModelJobJobTitles) UnmarshalBinary(b []byte) error {
	var res SovrenParserModelJobJobTitles
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
