// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenSaasDomainNormalizationResponseModel sovren saas domain normalization response model
//
// swagger:model Sovren.Saas.Domain.NormalizationResponseModel
type SovrenSaasDomainNormalizationResponseModel struct {

	// key
	Key string `json:"Key,omitempty"`

	// name
	Name string `json:"Name,omitempty"`

	// timestamp
	Timestamp string `json:"Timestamp,omitempty"`
}

// Validate validates this sovren saas domain normalization response model
func (m *SovrenSaasDomainNormalizationResponseModel) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren saas domain normalization response model based on context it is used
func (m *SovrenSaasDomainNormalizationResponseModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenSaasDomainNormalizationResponseModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenSaasDomainNormalizationResponseModel) UnmarshalBinary(b []byte) error {
	var res SovrenSaasDomainNormalizationResponseModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
