// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenParserModelJobJobDegree sovren parser model job job degree
//
// swagger:model Sovren.Parser.Model.Job.JobDegree
type SovrenParserModelJobJobDegree struct {

	// name
	Name string `json:"Name,omitempty"`

	// type
	Type string `json:"Type,omitempty"`
}

// Validate validates this sovren parser model job job degree
func (m *SovrenParserModelJobJobDegree) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren parser model job job degree based on context it is used
func (m *SovrenParserModelJobJobDegree) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenParserModelJobJobDegree) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenParserModelJobJobDegree) UnmarshalBinary(b []byte) error {
	var res SovrenParserModelJobJobDegree
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
