// Code generated by go-swagger; DO NOT EDIT.

package go_sovren_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SovrenSaasDomainUpdateSkillRequest sovren saas domain update skill request
//
// swagger:model Sovren.Saas.Domain.UpdateSkillRequest
type SovrenSaasDomainUpdateSkillRequest struct {

	// content
	Content []string `json:"Content"`
}

// Validate validates this sovren saas domain update skill request
func (m *SovrenSaasDomainUpdateSkillRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this sovren saas domain update skill request based on context it is used
func (m *SovrenSaasDomainUpdateSkillRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SovrenSaasDomainUpdateSkillRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SovrenSaasDomainUpdateSkillRequest) UnmarshalBinary(b []byte) error {
	var res SovrenSaasDomainUpdateSkillRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
